# -*- coding: utf-8 -*-
from __future__ import unicode_literals
"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""


import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# DATA_DIR = BASE_DIR
DATA_DIR = '/data/oms'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'nvo4y3w)#13$$4(ok+eqb30no1alvqyn2m=he(u_4_^n%d!j3f'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
# ALLOWED_HOSTS = []

DEBUG = True
ALLOWED_HOSTS = ['*']

# DEBUG = False
# ALLOWED_HOSTS = ['*']


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'sql',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Third party
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',
    # Custom
    'project.middlewares.LogMiddleware',
    'project.middlewares.LoginRequiredMiddleware',
    'project.middlewares.StripMiddleware',
]


ROOT_URLCONF = 'project.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'project.wsgi.application'


SESSION_COOKIE_AGE = 5 * 24 * 3600


URL_WHITE_LIST = (
    r'^/admin.*$',
    r'^/for_sign_in.html$',
    r'^/sign_in$',
    r'^/sign_out.*$',
)
URL_BLACK_LIST = (
    r'/(.*)$',
)


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # },
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'oms',
        'USER': 'oms',
        'PASSWORD': '123',
        'HOST': '127.0.0.1',
        'PORT': 3306,
        'OPTIONS': {
            'init_command': 'SET NAMES utf8, sql_mode="STRICT_TRANS_TABLES"',
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators
U = 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'
M = 'django.contrib.auth.password_validation.MinimumLengthValidator'
C = 'django.contrib.auth.password_validation.CommonPasswordValidator'
N = 'django.contrib.auth.password_validation.NumericPasswordValidator'
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': U}, {'NAME': M}, {'NAME': C}, {'NAME': N}
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/
LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

# USE_TZ = True
USE_TZ = False



# https://docs.djangoproject.com/en/1.11/ref/settings/
# https://docs.djangoproject.com/en/1.11/topics/i18n/translation/
# https://github.com/django/django/tree/master/django/conf/locale
from django.utils.translation import ugettext_lazy as _
LANGUAGES = [
    ('en', _('English')),
    ('zh-hans', _('Simplified Chinese')),
]
# LANGUAGE_CODE = 'en-us'
# LANGUAGE_CODE = 'zh-hans'
# LANGUAGE_COOKIE_NAME = 'django_language'
LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
    os.path.join(DATA_DIR),
)


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': (
                '%(asctime)s,%(msecs)03d '
                '[%(name)s:%(funcName)s:%(lineno)d] '
                '%(levelname)-5s - %(message)s'
            ),
            'datefmt' : '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'rotatingFile': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/project.log'),
            'maxBytes': 1024 * 1024 * 20,
            'backupCount': 50,
            'formatter': 'standard',
        },
        'timedRotatingFile': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/project.log'),
            'when':'midnight',
            'interval': 1,
            'backupCount': 90,
            'formatter':'standard',
        },
    },
    'loggers': {
        '': {
            'handlers': ['rotatingFile'],
            'level': 'INFO',
        },
    },
}


OPS_MAIL = 'Admin <notification@notification123.com>'
MAIL_ENABLED = False
# MAIL_ENABLED = True


EMAIL_HOST = 'smtp.exmail.qq.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'notification@notification123.com'
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_SSL = True


CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True


REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 1
